USE [BDCLIENTES]
GO
/****** Object:  Table [dbo].[CLIENTES]    Script Date: 19/02/2022 20:10:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTES](
	[CLI_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CLI_CGC] [varchar](20) NULL,
	[CLI_NOME] [varchar](50) NULL,
	[CLI_NASCIMENTO] [varchar](10) NULL,
	[CLI_TELEFONE] [varchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[CLI_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ENDERECO]    Script Date: 19/02/2022 20:10:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ENDERECO](
	[END_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[END_CEP] [varchar](50) NULL,
	[END_ENDERECO] [varchar](50) NULL,
	[END_NUMERO] [varchar](50) NULL,
	[END_COMPLEMENTO] [varchar](50) NULL,
	[END_BAIRRO] [varchar](20) NULL,
	[END_ESTADO] [varchar](10) NULL,
	[END_CIDADE] [varchar](20) NULL,
	[END_CGC] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[END_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
